### ISSUE TITLE
e::equals_max_precision tests fail on i386

### ISSUE THREAD

**Issue by jonassmedegaard** [kaj/rsass#182]
With release v0.28.2, two tests fail on i386:
```
failures:

---- values::calculation::calc::constant::e::equals_max_precision stdout ----
thread 'values::calculation::calc::constant::e::equals_max_precision' panicked at 'assertion failed: `(left == right)`
  left: `"a {\n  b: false;\n}\n"`,
 right: `"a {\n  b: true;\n}\n"`', rsass/tests/spec/values/calculation/calc/constant.rs:32:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: spec::values::calculation::calc::constant::e::equals_max_precision
             at ./tests/spec/values/calculation/calc/constant.rs:32:9
   5: spec::values::calculation::calc::constant::e::equals_max_precision::{{closure}}
             at ./tests/spec/values/calculation/calc/constant.rs:31:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- values::calculation::calc::constant::pi::equals_max_precision stdout ----
thread 'values::calculation::calc::constant::pi::equals_max_precision' panicked at 'assertion failed: `(left == right)`
  left: `"a {\n  b: false;\n}\n"`,
 right: `"a {\n  b: true;\n}\n"`', rsass/tests/spec/values/calculation/calc/constant.rs:333:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: spec::values::calculation::calc::constant::pi::equals_max_precision
             at ./tests/spec/values/calculation/calc/constant.rs:333:9
   5: spec::values::calculation::calc::constant::pi::equals_max_precision::{{closure}}
             at ./tests/spec/values/calculation/calc/constant.rs:332:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    values::calculation::calc::constant::e::equals_max_precision
    values::calculation::calc::constant::pi::equals_max_precision
```

Full build log: https://buildd.debian.org/status/fetch.php?pkg=rsass&arch=i386&ver=0.28.2-1&stamp=1691158787&raw=0

**Comment by kaj** [comment]
This is similar to #168 .  I'm not sure if it is a problem with 64-bit floats on a 32-bit architecture or if it may be a problem with my code for converting "text" floating point numbers to f64 floating point numbers.  As I do that conversion through a `num-rational` value, that may also contribute.

Checking for exact equality in floating points numbers is often problematic.  Maybe the tests (in [sass-spec](https://github.com/sass/sass-spec.git)) should be modified to check that the value falls inside a suitably small range?

**Comment by kaj** [comment]
This isn't mentioned in #209, a lot of code related to parsing text floating point numbers has changed since it was reported, and I can't reproduce it (due to not having an i386 handy), so I'll just assume that this is actually fixed.

**Comment by jonassmedegaard** [comment]
I tried last night to re-enable these tests, and can confirm that that particular test no longer fails on i386.

**Comment by jonassmedegaard** [comment]
Correction: the test `core_functions::math::log::base::one_fuzzy` still fails.

**Comment by jonassmedegaard** [comment]
The still failing test can be seen [here](https://buildd.debian.org/status/fetch.php?pkg=rsass&arch=i386&ver=0.29.0-3%2Bexp2&stamp=1740873268&raw=0)

**Comment by jonassmedegaard** [comment]
The reason this failure isn't mentioned in #209 is that I have generally omitted the tests reported here in later builds for Debian.

**Comment by kaj** [comment]
Ah well.  Those tests are kind of silly anyway (checking for equality on floating point calculations).  So it's probably fine to just leave that test disabled on i386 and leave this issue closed.
